repl:loadplugin 'linenoise'
repl:loadplugin 'history'
repl:loadplugin 'completion'
repl:loadplugin 'autoreturn'
repl:loadplugin 'filename_completion'
repl:loadplugin 'pretty_print'
repl:loadplugin 'keep_last_eval'
